name: bloc_architecture
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.1

  # dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # route
  go_router: ^6.0.1
  
  # data class
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # graphql 
  graphql: ^5.1.2

  # local database
  hive_flutter: ^1.1.0

  # logger
  logger: ^1.1.0

  # util
  collection: ^1.16.0
  rxdart: ^0.27.7
  infinite_scroll_pagination: ^3.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test:
  build_runner: 
  freezed: 
  json_serializable: 
  hive_generator: 
  mocktail:
  retrofit_generator: 
  injectable_generator:

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
